### ISSUE TITLE
Multiple hack issues.

### ISSUE THREAD

**Issue by cortexrampage** [futzumi/Moby-Max-Hack#16]
First order of buisness, what happened to the old ui? The one where you right clicked and got a little menu? I liked that one so much better!

Secondly, what does the focus time hack do? Does it work on math lessons?

First three letters of my name for some reason : sil

Oh, and an idea. Could you make the auto answer mode a little more customizable? Like maybe make it get a few questions wrong every now and then, or add a feature that makes the questions take different time increments to answer for realism?

**Comment by futzumi** [comment]
the old UI had to be reverted back because it made the hack insecure and easy to patch. The focus time hack adds to your lifetime time. So if you go to the balloons, select time summery, it should add an hour to it. I have many unreleased features to the hack too. I made one where the time appears in a certain subject, for example, math. but I'm waiting for the first ones to be patched

**Comment by phillipbruh** [comment]
nice try moby max devs

**Comment by futzumi** [comment]
ok I'll look into it

**Comment by futzumi** [comment]
we can prob add anything you want, although they have "good" security, some guy gave us this secret code and said he'd be fired if he told anyone. idk but that gave us access to the database with everyone's info

**Comment by phillipbruh** [comment]
yea even if they dont pay us we can tell a news company that we found it and become locally famous.

**Comment by futzumi** [comment]
Im pretty sure we get paid either way lol
